// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlansImport } from './routes/plans'
import { Route as PlansIndexImport } from './routes/plans.index'
import { Route as PlansPlanIdImport } from './routes/plans.$planId'

// Create Virtual Routes

const DashboardLazyImport = createFileRoute('/dashboard')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const PlansRoute = PlansImport.update({
  path: '/plans',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PlansIndexRoute = PlansIndexImport.update({
  path: '/',
  getParentRoute: () => PlansRoute,
} as any)

const PlansPlanIdRoute = PlansPlanIdImport.update({
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/plans': {
      preLoaderRoute: typeof PlansImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/plans/$planId': {
      preLoaderRoute: typeof PlansPlanIdImport
      parentRoute: typeof PlansImport
    }
    '/plans/': {
      preLoaderRoute: typeof PlansIndexImport
      parentRoute: typeof PlansImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PlansRoute.addChildren([PlansPlanIdRoute, PlansIndexRoute]),
  AboutLazyRoute,
  DashboardLazyRoute,
])
